name: Deploy Admin Frontend to Google Cloud Run
on:
  push:
    branches: [main, staging, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
      
      - name: Enable Corepack
        run: corepack enable
        
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            export REACT_APP_API_BASE_URL=https://api-dev.fanflix.be
            export REACT_APP_TALENT_BASE_URL=https://studio-dev.fanflix.be
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            export REACT_APP_API_BASE_URL=https://api-staging.fanflix.be
            export REACT_APP_TALENT_BASE_URL=https://studio-staging.fanflix.be
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            export REACT_APP_API_BASE_URL=https://api.fanflix.be
            export REACT_APP_TALENT_BASE_URL=https://studio.fanflix.be
          fi
          yarn build

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'


      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: |
          gcloud run deploy fanflix-admin-dev \
            --source . \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          gcloud run deploy fanflix-admin-staging \
            --source . \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud run deploy fanflix-admin \
            --source . \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080