name: Deploy Admin Frontend to Google Cloud Run
on:
  push:
    branches: [main, staging, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.18.0'
          cache: 'yarn'
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Create environment file
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "REACT_APP_API_BASE_URL=https://fanflix-api-dev-237749300373.europe-west1.run.app" > .env
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "REACT_APP_API_BASE_URL=https://fanflix-api-staging-237749300373.europe-west1.run.app" > .env
          elif [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "REACT_APP_API_BASE_URL=https://fanflix-api-237749300373.europe-west1.run.app" > .env
          fi
        
      - name: Build
        run: yarn build

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Create Dockerfile
        run: |
          cat > Dockerfile << 'EOF'
          FROM nginx:alpine
          COPY build /usr/share/nginx/html
          COPY nginx.conf /etc/nginx/conf.d/default.conf
          EXPOSE 8080
          CMD ["nginx", "-g", "daemon off;"]
          EOF

      - name: Create nginx config
        run: |
          cat > nginx.conf << 'EOF'
          server {
            listen 8080;
            server_name _;
            root /usr/share/nginx/html;
            index index.html;
            
            location / {
              try_files $uri $uri/ /index.html;
            }
            
            location /static/ {
              expires 1y;
              add_header Cache-Control "public, immutable";
            }
          }
          EOF

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: |
          gcloud run deploy fanflix-admin-dev \
            --source . \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080

      - name: Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        run: |
          gcloud run deploy fanflix-admin-staging \
            --source . \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          gcloud run deploy fanflix-admin \
            --source . \
            --platform managed \
            --region europe-west1 \
            --allow-unauthenticated \
            --port 8080